
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(whoami)
> 
> test_check("whoami")
[ FAIL 6 | WARN 0 | SKIP 2 | PASS 9 ]

══ Skipped tests ═══════════════════════════════════════════════════════════════
• empty test (1)
• On CRAN (1)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-email.R:6:3'): Email address works ─────────────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-email.R:6:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-fallbacks.R:6:3'): username() falls back ───────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-fallbacks.R:6:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-fallbacks.R:13:3'): fullname() falls back ──────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-fallbacks.R:13:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-fallbacks.R:19:3'): email_address() falls back ─────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-fallbacks.R:19:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-fallbacks.R:25:3'): gh_username() falls back ───────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-fallbacks.R:25:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-fullname.R:6:3'): fullname fallback ────────────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called ‘mockery’
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-fullname.R:6:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)

[ FAIL 6 | WARN 0 | SKIP 2 | PASS 9 ]
Error: Test failures
Execution halted
