
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(ps)
> 
> if (ps::ps_is_supported() && Sys.getenv("R_COVR", "") != "true" &&
+     Sys.getenv("NOT_CRAN") != "" ) {
+   reporter <- ps::CleanupReporter(testthat::SummaryReporter)$new()
+ } else {
+   reporter <- "summary"
+ }
> 
> if (ps_is_supported()) test_check("ps", reporter = reporter)
cleanup-reporter: .......................................................SSS
common: .....................................................1.SSSSS
connections: ...............SSSSSSSSS
finished: S
kill-tree: ....SSSSSSS
linux: ......S
macos: 
pid-reuse: .........................................234
posix-zombie: ...............................................................
posix: .S..........
ps: .
system: ..................
utils: ................
windows: 
winver: ......

══ Skipped ═════════════════════════════════════════════════════════════════════
1. Network cleanup, test, fail ('test-cleanup-reporter.R:348:3') - Reason: On CRAN

2. Network cleanup, unit: testsuite ('test-cleanup-reporter.R:371:3') - Reason: On CRAN

3. Network connections already open are ignored ('test-cleanup-reporter.R:399:3') - Reason: On CRAN

4. children ('test-common.R:236:3') - Reason: On CRAN

5. num_fds ('test-common.R:265:3') - Reason: On CRAN

6. open_files ('test-common.R:281:3') - Reason: On CRAN

7. interrupt ('test-common.R:298:3') - Reason: On CRAN

8. cpu affinity ('test-common.R:315:3') - Reason: On CRAN

9. UNIX sockets with path ('test-connections.R:43:3') - Reason: socat is not available

10. TCP ('test-connections.R:66:3') - Reason: On CRAN

11. TCP on loopback ('test-connections.R:86:3') - Reason: socat is not available

12. UDP ('test-connections.R:120:3') - Reason: On CRAN

13. UDP on loopback ('test-connections.R:146:3') - Reason: socat is not available

14. TCP6 ('test-connections.R:178:3') - Reason: socat is not available

15. TCP6 on loopback ('test-connections.R:199:3') - Reason: socat is not available

16. UDP6 ('test-connections.R:237:3') - Reason: Needs working IPv6 connection

17. UDP6 on loopback ('test-connections.R:262:3') - Reason: socat is not available

18. process already finished ('test-finished.R:3:3') - Reason: On CRAN

19. kill_tree ('test-kill-tree.R:12:3') - Reason: On CRAN

20. kill_tree, grandchild ('test-kill-tree.R:59:3') - Reason: On CRAN

21. kill_tree, orphaned grandchild ('test-kill-tree.R:127:3') - Reason: On CRAN

22. with_process_cleanup ('test-kill-tree.R:155:3') - Reason: On CRAN

23. find_tree ('test-kill-tree.R:182:3') - Reason: On CRAN

24. find_tree, grandchild ('test-kill-tree.R:207:3') - Reason: On CRAN

25. find_tree, orphaned grandchild ('test-kill-tree.R:255:3') - Reason: On CRAN

26. memory_info ('test-linux.R:30:3') - Reason: On CRAN

27. terminal ('test-posix.R:14:3') - Reason: no terminal

══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure ('test-common.R:227:5'): kill ────────────────────────────────────
p1$get_exit_status() (`actual`) not equal to -signals()$SIGKILL (`expected`).

  `actual`: -15
`expected`:  -9

── 2. Failure ('test-pid-reuse.R:43:3'): pid reuse ─────────────────────────────
`err` is not an S3 object
Backtrace:
 1. ps (local) chk(ps_kill(p))
      at test-pid-reuse.R:43:3
 2. testthat::expect_s3_class(err, "no_such_process")
      at test-pid-reuse.R:24:5

── 3. Failure ('test-pid-reuse.R:43:3'): pid reuse ─────────────────────────────
`err` is not an S3 object
Backtrace:
 1. ps (local) chk(ps_kill(p))
      at test-pid-reuse.R:43:3
 2. testthat::expect_s3_class(err, "ps_error")
      at test-pid-reuse.R:25:5

── 4. Error ('test-pid-reuse.R:43:3'): pid reuse ───────────────────────────────
Error in `err$pid`: $ operator is invalid for atomic vectors
Backtrace:
 1. ps (local) chk(ps_kill(p))
      at test-pid-reuse.R:43:3
 2. testthat::expect_equal(err$pid, zpid)
      at test-pid-reuse.R:26:5
 3. testthat::quasi_label(enquo(object), label, arg = "object")
 4. rlang::eval_bare(expr, quo_get_env(quo))

══ DONE ════════════════════════════════════════════════════════════════════════
I believe in you!
Error: Test failures
No deferred expressions to run
Execution halted
